
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/microservice
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #data:
    #mongodb:
      #uri: mongodb://localhost:27017
      #database: microservices
  application:
    name: RATING-SERVICE
server:
  port: 8083




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-69271799.okta.com/oauth2/default
    audience: api://default